Repository quarkus-qe/quarkus-test-framework, pull requests merged in 2024-10, with the labels that each got.

#1359 Always use dependency version managed by BOM when forced dependency version is not specified
  quarkus-test-core/src/main/java/io/quarkus/test/services/Dependency.java
  quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/ProdQuarkusApplicationManagedResourceBuilder.java
  quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/QuarkusApplicationManagedResourceBuilder.java
  quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/QuarkusMavenPluginBuildHelper.java
Labels: triage/backport-1.5?

#1362 Fix file separator used by Quarkus Maven Plugin build strategy when custom files are added to be platform independent
  quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/QuarkusMavenPluginBuildHelper.java
Labels: triage/backport-1.5?

#1365 Add DisabledOnAarch64Native annotation
  quarkus-test-core/src/main/java/io/quarkus/test/scenarios/annotations/DisabledOnAarch64Native.java
  quarkus-test-core/src/main/java/io/quarkus/test/scenarios/annotations/DisabledOnAarch64NativeCondition.java
Labels: triage/backport-1.5?

#1369 [1.5.z] Add DisabledOnAarch64Native annotation
  quarkus-test-core/src/main/java/io/quarkus/test/scenarios/annotations/DisabledOnAarch64Native.java
  quarkus-test-core/src/main/java/io/quarkus/test/scenarios/annotations/DisabledOnAarch64NativeCondition.java
Labels: triage/flaky-test

#1377 Move DisabledOnRHBQWindowsConditions from testsuite to framework
  quarkus-test-core/src/main/java/io/quarkus/test/scenarios/annotations/DisabledOnRHBQWindowsConditions.java
  quarkus-test-core/src/main/java/io/quarkus/test/scenarios/annotations/DisabledOnRHBQandWindows.java
Labels: triage/backport-1.5?

#1378 Add closing resources in quarkus cli as windows is more strict
  quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
  quarkus-test-cli/src/main/java/io/quarkus/test/util/YamlPropertiesHandler.java
Labels: triage/backport-1.4?, triage/backport-1.5?

#1380 Add @DisabledOnFipsAndNative annotation and drop @DisabledOnFipsAndJava17
  quarkus-test-core/src/main/java/io/quarkus/test/scenarios/annotations/DisabledOnFipsAndNative.java
  quarkus-test-core/src/main/java/io/quarkus/test/scenarios/annotations/DisabledOnFipsAndNativeCondition.java
Labels: triage/backport-1.5?
