Repository quarkus-qe/quarkus-test-framework, pull requests merged in 2024-09, with the labels that each got.

#1270 Support OpenShift certificate serving used with TLS registry
  examples/https/pom.xml
  examples/https/src/test/java/io/quarkus/qe/OpenShiftServingCertificatesIT.java
  examples/https/src/test/java/io/quarkus/qe/hero/Hero.java
  examples/https/src/test/java/io/quarkus/qe/hero/HeroClient.java
  examples/https/src/test/java/io/quarkus/qe/hero/HeroClientResource.java
  examples/https/src/test/java/io/quarkus/qe/hero/HeroResource.java
  examples/https/src/test/resources/test.properties
  quarkus-test-core/src/main/java/io/quarkus/test/security/certificate/CertificateBuilder.java
  quarkus-test-core/src/main/java/io/quarkus/test/security/certificate/CertificateBuilderImpl.java
  quarkus-test-core/src/main/java/io/quarkus/test/security/certificate/ServingCertificateConfig.java
  quarkus-test-core/src/main/java/io/quarkus/test/services/Certificate.java
  quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/QuarkusApplicationManagedResourceBuilder.java
  quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
  quarkus-test-openshift/src/main/java/io/quarkus/test/openshift/utils/OpenShiftPropertiesUtils.java
  quarkus-test-openshift/src/main/java/io/quarkus/test/services/containers/OpenShiftContainerManagedResource.java
  quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/OpenShiftQuarkusApplicationManagedResource.java
  quarkus-test-openshift/src/main/java/io/quarkus/test/services/quarkus/TemplateOpenShiftQuarkusApplicationManagedResource.java
  quarkus-test-openshift/src/main/resources/openshift-deployment-template.yml
  quarkus-test-openshift/src/main/resources/quarkus-build-openshift-template.yml
  quarkus-test-openshift/src/main/resources/quarkus-registry-openshift-template.yml
Labels: triage/backport-1.5?

#1272 Support gRPC TLS communication and TLS registry and FW support for gRPC on same server
  examples/grpc/pom.xml
  examples/grpc/src/main/java/io/quarkus/qe/grpc/HelloService.java
  examples/grpc/src/main/proto/helloworld.proto
  examples/grpc/src/main/resources/META-INF/resources/server.keystore
  examples/grpc/src/main/resources/META-INF/resources/server.truststore
  examples/grpc/src/test/java/io/quarkus/qe/grpc/DevModeGrpcServiceIT.java
  examples/grpc/src/test/java/io/quarkus/qe/grpc/GrpcMtlsTlsRegistryIT.java
  examples/grpc/src/test/java/io/quarkus/qe/grpc/GrpcServiceIT.java
  examples/grpc/src/test/java/io/quarkus/qe/grpc/GrpcTlsRegistryIT.java
  quarkus-test-core/src/main/java/io/quarkus/test/security/certificate/Certificate.java
  quarkus-test-core/src/main/java/io/quarkus/test/security/certificate/ClientCertificateImpl.java
  quarkus-test-core/src/main/java/io/quarkus/test/security/certificate/PemClientCertificate.java
  quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/LocalhostQuarkusApplicationManagedResource.java
  quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/model/QuarkusProperties.java
  quarkus-test-service-grpc/pom.xml
  quarkus-test-service-grpc/src/main/java/io/quarkus/test/bootstrap/CloseableManagedChannel.java
  quarkus-test-service-grpc/src/main/java/io/quarkus/test/bootstrap/GrpcService.java
Labels: triage/flaky-test, triage/backport-1.5?

#1276 Support TLS registry with Kafka Strimzi for SASL_SSL and SSL scenarios
  examples/kafka/pom.xml
  examples/kafka/src/main/java/io/quarkus/qe/TlsRegistryResource.java
  examples/kafka/src/test/java/io/quarkus/qe/StrimziKafkaWithTlsRegistryAndSaslSslMessagingIT.java
  quarkus-test-service-kafka/src/main/java/io/quarkus/test/services/KafkaContainer.java
  quarkus-test-service-kafka/src/main/java/io/quarkus/test/services/containers/KafkaContainerManagedResourceBuilder.java
  quarkus-test-service-kafka/src/main/java/io/quarkus/test/services/containers/StrimziKafkaContainerManagedResource.java
Labels: triage/backport-1.5?

#1277 Support Jaeger TLS communication with Quarkus OTel OTLP collector configured from TLS registry
  examples/jaeger/src/test/java/io/quarkus/qe/OpenTelemetryJaegerTlsIT.java
  quarkus-test-core/src/main/java/io/quarkus/test/security/certificate/Certificate.java
  quarkus-test-service-jaeger/src/main/java/io/quarkus/test/bootstrap/JaegerService.java
  quarkus-test-service-jaeger/src/main/java/io/quarkus/test/services/JaegerContainer.java
  quarkus-test-service-jaeger/src/main/java/io/quarkus/test/services/containers/JaegerContainerManagedResourceBuilder.java
  quarkus-test-service-jaeger/src/main/java/io/quarkus/test/services/containers/JaegerGenericDockerContainerManagedResource.java
Labels: triage/backport-1.5?

#1280 Support Mutiny HTTPS with PEM certificates
  quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/RestService.java
Labels: triage/backport-1.5?

#1281 Fix PEM certificate generation with disabled TLS registry
  quarkus-test-core/src/main/java/io/quarkus/test/security/certificate/Certificate.java
Labels: triage/backport-1.5?

#1296 Fix OpenShift certificate serving flakiness
  examples/https/src/test/java/io/quarkus/qe/OpenShiftServingCertificatesIT.java
  quarkus-test-core/src/main/java/io/quarkus/test/services/Certificate.java
  quarkus-test-openshift/src/main/java/io/quarkus/test/bootstrap/inject/OpenShiftClient.java
Labels: triage/backport-1.5?

#1297 Drop debugging options for Windows native race
  .github/workflows/daily.yaml
  quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/ProdQuarkusApplicationManagedResourceBuilder.java
Labels: triage/backport-1.4?, triage/backport-1.5?

#1299 Fix framework compilation error after change of `initConfiguration` signature in Quarkus config builder change
  quarkus-test-core/src/main/java/io/quarkus/test/services/quarkus/QuarkusApplicationManagedResourceBuilder.java
Labels: triage/backport-1.5?

#1298 Fix log duplication we experienced in Jenkins when testing RHBQ 3.8
  quarkus-test-core/src/main/java/io/quarkus/test/logging/Log.java
Labels: triage/backport-1.4?, triage/backport-1.5?

#1303 Move RHBQPlatformAppManager to framework
  quarkus-test-cli/src/main/java/io/quarkus/test/util/QuarkusCLIUtils.java
  quarkus-test-cli/src/main/java/io/quarkus/test/util/RHBQPlatformAppManager.java
Labels: triage/backport-1.4?

#1305 Fix PostgreSQL waiting strategy for image from Red Hat container registry
  quarkus-test-service-database/src/main/java/io/quarkus/test/bootstrap/PostgresqlService.java
Labels: triage/backport-1.4?, triage/backport-1.5?
