Repository quarkus-qe/quarkus-test-framework, pull requests merged in 2024-07, with the labels that each got.

#1174 Add Kubernetes jobs to GH Actions workflow
  .github/configure-load-balancer.sh
  .github/workflows/daily.yaml
  .github/workflows/pr.yaml
  quarkus-test-kubernetes/pom.xml
Labels: triage/flaky-test

#1192 Remove PR Kubernetes workflow
  .github/workflows/pr.yaml
Labels: triage/flaky-test

#1196 Workaround Groovy conflicts in Debug examples as daily build is failing
  examples/debug/src/test/resources-filtered/project/classic/src/test/java/io/quarkus/qe/debug/HelloIT.java
  quarkus-test-core/src/main/java/io/quarkus/test/bootstrap/RestService.java
  quarkus-test-core/src/main/java/io/quarkus/test/debug/SureFireCommunicationHelper.java
Labels: triage/flaky-test

#1197 Fix NPE on Windows during certificate generation as File path separator differs to actual one
  quarkus-test-core/src/main/java/io/quarkus/test/security/certificate/Certificate.java
Labels: triage/backport-1.4?

#1201 Update release version checker
  .github/pull_request_template.md
  .github/workflows/check-release-version.yml
Labels: triage/backport-1.3?, triage/backport-1.4?

#1202 [1.4.z] Update release version checker
  .github/pull_request_template.md
  .github/workflows/check-release-version.yml
Labels: DON'T MERGE

#1209 Fix and extend release version checker
  .github/workflows/check-release-version.yml
  RELEASE.md
Labels: triage/flaky-test

#1207 Bump strimzi kafka testcontainer to 0.107.0
  pom.xml
Labels: triage/backport-1.3?, triage/backport-1.4?
